### ISSUE TITLE
release:translate operation does not work in Docker environment

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/cow#178] opened 2020-06-28 21:10 UTC
This is likely caused by the lack of any DB solution being applied to the Docker image. Installing and configuring SQLite may be an easy, lightweight way to solve the issue.

#### ACs

- [ ] `release:translate` command works correctly

**Comment by dnsl48** [comment] 2020-07-15 23:27
I could not reproduce the issue. `release:translate` worked for me.

**Comment by brynwhyman** [comment] 2021-09-13 05:24
Closing as per the above comment

**Closed by brynwhyman** 2021-09-13 05:24 UTC
